{*
    A11y One — accessible ticket custom fields.
    Author: Can Kirca <cankirca@gmail.com> — https://github.com/cankirca

    Accessibility notes vs parent twenty-one:
      - Each field keeps a persistent visible <label for="customfield{id}">, which
        matches the id WHMCS core assigns to most generated custom-field inputs.
      - When a field has a description, it is rendered with id="customfield{id}_desc"
        and referenced from the input via aria-describedby (added by a11y-one.js,
        which can reach the core-generated control by its known id). This avoids
        forking core's field-rendering markup ($customfield.input is opaque).
    DEFERRAL: the inner control HTML in $customfield.input is generated by WHMCS
    core and not all field types (e.g. some dropdowns) expose an id we can target;
    those edge cases are tracked for the WS-I site-wide field-labelling sweep.
*}
{foreach $customfields as $customfield}
    <div class="form-group">
        <label for="customfield{$customfield.id}">{$customfield.name}</label>
        {$customfield.input}
        {if $customfield.description}
            <p class="form-text text-muted" id="customfield{$customfield.id}_desc">{$customfield.description}</p>
        {/if}
    </div>
{/foreach}
